server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wxems?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

  redis:
    database: 5
    host: 127.0.0.1
    password: 123456
    port: 6379
    timeout: 3000
    pool:
      max-idle: 100
      min-idle: 10
      max-active: 200
      max-wait: 1000


logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
    hibernate: ERROR
#  path: ${catalina.home}/logs/configmanager-DetailLog.log